### ISSUE TITLE
Ports need to be defined in overlays

### ISSUE THREAD

**Issue by lanzafame** [lanzafame/ipfs-cluster-k8s#1]
The combination of services exposing default ipfs and ipfs-cluster ports and External-DNS results in more ports being exposed to public net then desired. With kustomize's position of overlays don't remove config, only add and update, ports need to be exposed by overlay configurations so that they can control everything that they want to expose and nothing more.

**Comment by olizilla** [comment]
The cluster docs still show all the ports https://github.com/ipfs/ipfs-cluster-website/blob/master/content/documentation/guides/k8s.md#defining-a-statefulset

**Comment by lanzafame** [comment]
I am not sure if I really want to update that. In the sense, it was always a guide and not a production hardened deployment configuration. Plus, if I am reworking it, there is a bunch of things that need fixing.
